{
 "title": "Dashboard",
 "tags": [ "阿里云" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ecs", "query": "num(ecs)" },
   { "name": "rds", "query": "num(rds)" },
   { "name": "slb", "query": "num(slb)" },
   { "name": "eip", "query": "num(eip)" },
   { "name": "redis", "query": "num(redis)" },
   { "name": "mongodb", "query": "num(mongodb)" },
   { "name": "all_eip", "query": "all(eip)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>Dashboard</span>\n</div>\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>云服务器：$ecs 台</span>\n</div>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>云数据库RDS：$rds 台</span>\n</div>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>MongoDb：$mongodb 台</span>\n</div>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>Redis：$redis 台</span>\n</div>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>负载均衡：$slb 个</span>\n</div>\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "content": "\n<div class=\"text-center dashboard-header\">\n  <span>弹性公网IP：$slb 个</span>\n</div>\n\n"
  },
  {
   "title": "CPU TOP 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "targets": [
    { "target": "cpu_top", "type": "timeserie" }
   ]
  },
  {
   "title": "内存 TOP 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "targets": [
    { "target": "mem_top", "type": "timeserie" }
   ]
  },
  {
   "title": "磁盘 TOP 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "targets": [
    { "target": "disk_top", "type": "timeserie" }
   ]
  },
  {
   "title": "CPU TOP10",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "cpu_top_10", "type": "timeserie" }
   ]
  },
  {
   "title": "内存 TOP10",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "mem_top_10", "type": "timeserie" }
   ]
  },
  {
   "title": "OSS存储量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "MeteringStorageUtilization",
     "period": "3600",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "总请求数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserTotalRequestCount",
     "period": "3600",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "OSS公网流入流量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserInternetRecv",
     "period": "3600",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "OSS公网流出流量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserInternetSend",
     "period": "3600",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "磁盘 TOP10",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "disk_top_10", "type": "timeserie" }
   ]
  },
  {
   "title": "流出带宽",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "dimensions": [
      "$all_eip",
      ","
     ],
     "metric": "net_tx.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "流入带宽",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "dimensions": [
      "$all_eip",
      ","
     ],
     "metric": "net_rx.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 } }
 ]
}